/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__great_module
#define __PYX_HAVE__great_module


#ifndef __PYX_HAVE_API__great_module

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *great_function(PyObject *, PyObject *);
__PYX_EXTERN_C DL_IMPORT(char) great_function_c(char const *, int);

#endif /* !__PYX_HAVE_API__great_module */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initgreat_module(void);
#else
PyMODINIT_FUNC PyInit_great_module(void);
#endif

#endif /* !__PYX_HAVE__great_module */
